import { PrismaClient } from '@prisma/client';

import { Personality, Language, Category } from '../src/modules/ouija/enums';

const prisma = new PrismaClient();

async function main() {
  console.log('Cargando datos en db...');

  // limpiar datos existentes
  console.log('Limpiando datos existentes...');
  await prisma.responseKeyword.deleteMany({});
  await prisma.keyword.deleteMany({});
  await prisma.fallbackResponse.deleteMany({});
  console.log('db limpia...\n');

  // Definir TODAS las 266 keywords únicas de una sola vez
  const keywords = [
    // Keywords en español (IDs 1-133)
    { id: 1, word: 'amor', language: Language.ES },
    { id: 2, word: 'pareja', language: Language.ES },
    { id: 3, word: 'romance', language: Language.ES },
    { id: 4, word: 'corazón', language: Language.ES },
    { id: 5, word: 'llegar', language: Language.ES },
    { id: 6, word: 'alma', language: Language.ES },
    { id: 7, word: 'gemela', language: Language.ES },
    { id: 8, word: 'esperar', language: Language.ES },
    { id: 9, word: 'paciencia', language: Language.ES },
    { id: 10, word: 'destino', language: Language.ES },
    { id: 11, word: 'sanar', language: Language.ES },
    { id: 12, word: 'curar', language: Language.ES },
    { id: 13, word: 'dolor', language: Language.ES },
    { id: 14, word: 'tiempo', language: Language.ES },
    { id: 15, word: 'trabajo', language: Language.ES },
    { id: 16, word: 'oportunidad', language: Language.ES },
    { id: 17, word: 'empleo', language: Language.ES },
    { id: 18, word: 'carrera', language: Language.ES },
    { id: 19, word: 'nuevo', language: Language.ES },
    { id: 20, word: 'pasión', language: Language.ES },
    { id: 21, word: 'vocación', language: Language.ES },
    { id: 22, word: 'propósito', language: Language.ES },
    { id: 23, word: 'seguir', language: Language.ES },
    { id: 24, word: 'camino', language: Language.ES },
    { id: 25, word: 'salud', language: Language.ES },
    { id: 26, word: 'cuerpo', language: Language.ES },
    { id: 27, word: 'enfermedad', language: Language.ES },
    { id: 28, word: 'mejorar', language: Language.ES },
    { id: 29, word: 'señales', language: Language.ES },
    { id: 30, word: 'escuchar', language: Language.ES },
    { id: 31, word: 'atención', language: Language.ES },
    { id: 32, word: 'familia', language: Language.ES },
    { id: 33, word: 'reconciliar', language: Language.ES },
    { id: 34, word: 'paz', language: Language.ES },
    { id: 35, word: 'unión', language: Language.ES },
    { id: 36, word: 'perdón', language: Language.ES },
    { id: 37, word: 'lazos', language: Language.ES },
    { id: 38, word: 'fortalecer', language: Language.ES },
    { id: 39, word: 'unir', language: Language.ES },
    { id: 40, word: 'muerte', language: Language.ES },
    { id: 41, word: 'renacer', language: Language.ES },
    { id: 42, word: 'transformar', language: Language.ES },
    { id: 43, word: 'ciclo', language: Language.ES },
    { id: 44, word: 'final', language: Language.ES },
    { id: 45, word: 'ancestros', language: Language.ES },
    { id: 46, word: 'proteger', language: Language.ES },
    { id: 47, word: 'espíritus', language: Language.ES },
    { id: 48, word: 'cuidar', language: Language.ES },
    { id: 49, word: 'guiar', language: Language.ES },
    { id: 50, word: 'futuro', language: Language.ES },
    { id: 51, word: 'cambios', language: Language.ES },
    { id: 52, word: 'positivo', language: Language.ES },
    { id: 53, word: 'venir', language: Language.ES },
    { id: 54, word: 'brillante', language: Language.ES },
    { id: 55, word: 'luz', language: Language.ES },
    { id: 56, word: 'esperanza', language: Language.ES },
    { id: 57, word: 'dinero', language: Language.ES },
    { id: 58, word: 'abundancia', language: Language.ES },
    { id: 59, word: 'fluir', language: Language.ES },
    { id: 60, word: 'riqueza', language: Language.ES },
    { id: 61, word: 'prosperidad', language: Language.ES },
    { id: 62, word: 'ahorrar', language: Language.ES },
    { id: 63, word: 'guardar', language: Language.ES },
    { id: 64, word: 'prudencia', language: Language.ES },
    { id: 65, word: 'espíritu', language: Language.ES },
    { id: 66, word: 'despertar', language: Language.ES },
    { id: 67, word: 'conciencia', language: Language.ES },
    { id: 68, word: 'evolución', language: Language.ES },
    { id: 69, word: 'meditar', language: Language.ES },
    { id: 70, word: 'respuestas', language: Language.ES },
    { id: 71, word: 'interior', language: Language.ES },
    { id: 72, word: 'buscar', language: Language.ES },
    { id: 73, word: 'momento', language: Language.ES },
    { id: 74, word: 'confiar', language: Language.ES },
    { id: 75, word: 'proceso', language: Language.ES },
    { id: 76, word: 'fe', language: Language.ES },
    { id: 77, word: 'creer', language: Language.ES },
    { id: 78, word: 'misterio', language: Language.ES },
    { id: 79, word: 'lunas', language: Language.ES },
    { id: 80, word: 'señal', language: Language.ES },
    { id: 81, word: 'rosa', language: Language.ES },
    { id: 82, word: 'espinas', language: Language.ES },
    { id: 83, word: 'oculto', language: Language.ES },
    { id: 84, word: 'peligro', language: Language.ES },
    { id: 85, word: 'decisión', language: Language.ES },
    { id: 86, word: 'elegir', language: Language.ES },
    { id: 87, word: 'sombras', language: Language.ES },
    { id: 88, word: 'oficina', language: Language.ES },
    { id: 89, word: 'cuidado', language: Language.ES },
    { id: 90, word: 'secretos', language: Language.ES },
    { id: 91, word: 'velo', language: Language.ES },
    { id: 92, word: 'otro', language: Language.ES },
    { id: 93, word: 'lado', language: Language.ES },
    { id: 94, word: 'susurros', language: Language.ES },
    { id: 95, word: 'mensaje', language: Language.ES },
    { id: 96, word: 'allá', language: Language.ES },
    { id: 97, word: 'niebla', language: Language.ES },
    { id: 98, word: 'mañana', language: Language.ES },
    { id: 99, word: 'incierto', language: Language.ES },
    { id: 100, word: 'péndulo', language: Language.ES },
    { id: 101, word: 'cambio', language: Language.ES },
    { id: 102, word: 'oro', language: Language.ES },
    { id: 103, word: 'tesoro', language: Language.ES },
    { id: 104, word: 'monedas', language: Language.ES },
    { id: 105, word: 'fortuna', language: Language.ES },
    { id: 106, word: 'ojo', language: Language.ES },
    { id: 107, word: 'ver', language: Language.ES },
    { id: 108, word: 'visión', language: Language.ES },
    { id: 109, word: 'voces', language: Language.ES },
    { id: 110, word: 'antiguo', language: Language.ES },
    { id: 111, word: 'llamar', language: Language.ES },
    { id: 112, word: 'cartas', language: Language.ES },
    { id: 113, word: 'suerte', language: Language.ES },
    { id: 114, word: 'decidido', language: Language.ES },
    { id: 115, word: 'espejo', language: Language.ES },
    { id: 116, word: 'verdad', language: Language.ES },
    { id: 117, word: 'revelar', language: Language.ES },
    { id: 118, word: 'mostrar', language: Language.ES },
    { id: 119, word: 'realidad', language: Language.ES },
    { id: 120, word: 'sufrir', language: Language.ES },
    { id: 121, word: 'siempre', language: Language.ES },
    { id: 122, word: 'roto', language: Language.ES },
    { id: 123, word: 'nunca', language: Language.ES },
    { id: 124, word: 'fracaso', language: Language.ES },
    { id: 125, word: 'acechar', language: Language.ES },
    { id: 126, word: 'caer', language: Language.ES },
    { id: 127, word: 'traición', language: Language.ES },
    { id: 128, word: 'enemigo', language: Language.ES },
    { id: 129, word: 'mal', language: Language.ES },
    { id: 130, word: 'débil', language: Language.ES },
    { id: 131, word: 'rencor', language: Language.ES },
    { id: 132, word: 'cerca', language: Language.ES },
    { id: 133, word: 'sangre', language: Language.ES },
    { id: 134, word: 'rondar', language: Language.ES },
    { id: 135, word: 'muertos', language: Language.ES },
    { id: 136, word: 'inquieto', language: Language.ES },
    { id: 137, word: 'tormento', language: Language.ES },
    { id: 138, word: 'oscuridad', language: Language.ES },
    { id: 139, word: 'negro', language: Language.ES },
    { id: 140, word: 'cruel', language: Language.ES },
    { id: 141, word: 'pobreza', language: Language.ES },
    { id: 142, word: 'perder', language: Language.ES },
    { id: 143, word: 'ruina', language: Language.ES },
    { id: 144, word: 'corrupción', language: Language.ES },
    { id: 145, word: 'perdida', language: Language.ES },
    { id: 146, word: 'vacío', language: Language.ES },
    { id: 147, word: 'demonios', language: Language.ES },
    { id: 148, word: 'observar', language: Language.ES },
    { id: 149, word: 'no', language: Language.ES },
    { id: 150, word: 'perdido', language: Language.ES },
    { id: 151, word: 'ganar', language: Language.ES },
    { id: 152, word: 'besos', language: Language.ES },
    { id: 153, word: 'alegría', language: Language.ES },
    { id: 154, word: 'volar', language: Language.ES },
    { id: 155, word: 'feliz', language: Language.ES },
    { id: 156, word: 'cupido', language: Language.ES },
    { id: 157, word: 'borracho', language: Language.ES },
    { id: 158, word: 'gracioso', language: Language.ES },
    { id: 159, word: 'loco', language: Language.ES },
    { id: 160, word: 'jefe', language: Language.ES },
    { id: 161, word: 'lunes', language: Language.ES },
    { id: 162, word: 'divertido', language: Language.ES },
    { id: 163, word: 'vitaminas', language: Language.ES },
    { id: 164, word: 'risas', language: Language.ES },
    { id: 165, word: 'bailar', language: Language.ES },
    { id: 166, word: 'fiesta', language: Language.ES },
    { id: 167, word: 'celebrar', language: Language.ES },
    { id: 168, word: 'abuela', language: Language.ES },
    { id: 169, word: 'galletas', language: Language.ES },
    { id: 170, word: 'dulce', language: Language.ES },
    { id: 171, word: 'fantasmas', language: Language.ES },
    { id: 172, word: 'amigo', language: Language.ES },
    { id: 173, word: 'bueno', language: Language.ES },
    { id: 174, word: 'sorpresas', language: Language.ES },
    { id: 175, word: 'brillar', language: Language.ES },
    { id: 176, word: 'lluvia', language: Language.ES },
    { id: 177, word: 'billetera', language: Language.ES },
    { id: 178, word: 'engordar', language: Language.ES },
    { id: 179, word: 'rico', language: Language.ES },
    { id: 180, word: 'pronto', language: Language.ES },
    { id: 181, word: 'ángeles', language: Language.ES },
    { id: 182, word: 'cielo', language: Language.ES },
    { id: 183, word: 'aura', language: Language.ES },
    { id: 184, word: 'arcoíris', language: Language.ES },
    { id: 185, word: 'color', language: Language.ES },
    { id: 186, word: 'pregunta', language: Language.ES },
    { id: 187, word: 'loca', language: Language.ES },
    { id: 188, word: 'risa', language: Language.ES },
    { id: 189, word: 'reír', language: Language.ES },
    { id: 190, word: 'casa', language: Language.ES },

    // Keywords en inglés (IDs 191-266)
    { id: 191, word: 'love', language: Language.EN },
    { id: 192, word: 'heart', language: Language.EN },
    { id: 193, word: 'ready', language: Language.EN },
    { id: 194, word: 'arrive', language: Language.EN },
    { id: 195, word: 'soul', language: Language.EN },
    { id: 196, word: 'patience', language: Language.EN },
    { id: 197, word: 'connection', language: Language.EN },
    { id: 198, word: 'true', language: Language.EN },
    { id: 199, word: 'wait', language: Language.EN },
    { id: 200, word: 'work', language: Language.EN },
    { id: 201, word: 'opportunity', language: Language.EN },
    { id: 202, word: 'career', language: Language.EN },
    { id: 203, word: 'job', language: Language.EN },
    { id: 204, word: 'new', language: Language.EN },
    { id: 205, word: 'calling', language: Language.EN },
    { id: 206, word: 'purpose', language: Language.EN },
    { id: 207, word: 'follow', language: Language.EN },
    { id: 208, word: 'path', language: Language.EN },
    { id: 209, word: 'health', language: Language.EN },
    { id: 210, word: 'heal', language: Language.EN },
    { id: 211, word: 'body', language: Language.EN },
    { id: 212, word: 'recovery', language: Language.EN },
    { id: 213, word: 'better', language: Language.EN },
    { id: 214, word: 'listen', language: Language.EN },
    { id: 215, word: 'wisdom', language: Language.EN },
    { id: 216, word: 'inner', language: Language.EN },
    { id: 217, word: 'family', language: Language.EN },
    { id: 218, word: 'bonds', language: Language.EN },
    { id: 219, word: 'strengthen', language: Language.EN },
    { id: 220, word: 'unity', language: Language.EN },
    { id: 221, word: 'forgiveness', language: Language.EN },
    { id: 222, word: 'peace', language: Language.EN },
    { id: 223, word: 'death', language: Language.EN },
    { id: 224, word: 'transformation', language: Language.EN },
    { id: 225, word: 'rebirth', language: Language.EN },
    { id: 226, word: 'cycle', language: Language.EN },
    { id: 227, word: 'change', language: Language.EN },
    { id: 228, word: 'ancestors', language: Language.EN },
    { id: 229, word: 'guide', language: Language.EN },
    { id: 230, word: 'spirit', language: Language.EN },
    { id: 231, word: 'protect', language: Language.EN },
    { id: 232, word: 'future', language: Language.EN },
    { id: 233, word: 'changes', language: Language.EN },
    { id: 234, word: 'bright', language: Language.EN },
    { id: 235, word: 'coming', language: Language.EN },
    { id: 236, word: 'destiny', language: Language.EN },
    { id: 237, word: 'shine', language: Language.EN },
    { id: 238, word: 'hope', language: Language.EN },
    { id: 239, word: 'money', language: Language.EN },
    { id: 240, word: 'abundance', language: Language.EN },
    { id: 241, word: 'flow', language: Language.EN },
    { id: 242, word: 'wealth', language: Language.EN },
    { id: 243, word: 'prosperity', language: Language.EN },
    { id: 244, word: 'save', language: Language.EN },
    { id: 245, word: 'prudent', language: Language.EN },
    { id: 246, word: 'awaken', language: Language.EN },
    { id: 247, word: 'consciousness', language: Language.EN },
    { id: 248, word: 'evolve', language: Language.EN },
    { id: 249, word: 'meditation', language: Language.EN },
    { id: 250, word: 'answers', language: Language.EN },
    { id: 251, word: 'clarity', language: Language.EN },
    { id: 252, word: 'time', language: Language.EN },
    { id: 253, word: 'moment', language: Language.EN },
    { id: 254, word: 'trust', language: Language.EN },
    { id: 255, word: 'process', language: Language.EN },
    { id: 256, word: 'faith', language: Language.EN },
    { id: 257, word: 'believe', language: Language.EN },
    { id: 258, word: 'mystery', language: Language.EN },
    { id: 259, word: 'moon', language: Language.EN },
    { id: 260, word: 'sign', language: Language.EN },
    { id: 261, word: 'roses', language: Language.EN },
    { id: 262, word: 'thorns', language: Language.EN },
    { id: 263, word: 'hidden', language: Language.EN },
    { id: 264, word: 'danger', language: Language.EN },
    { id: 265, word: 'choice', language: Language.EN },
    { id: 266, word: 'decision', language: Language.EN },
    { id: 267, word: 'split', language: Language.EN },
    { id: 268, word: 'shadows', language: Language.EN },
    { id: 269, word: 'office', language: Language.EN },
    { id: 270, word: 'warning', language: Language.EN },
    { id: 271, word: 'secrets', language: Language.EN },
    { id: 272, word: 'whisper', language: Language.EN },
    { id: 273, word: 'signs', language: Language.EN },
    { id: 274, word: 'poison', language: Language.EN },
    { id: 275, word: 'cure', language: Language.EN },
    { id: 276, word: 'medicine', language: Language.EN },
    { id: 277, word: 'blood', language: Language.EN },
    { id: 278, word: 'call', language: Language.EN },
    { id: 279, word: 'home', language: Language.EN },
    { id: 280, word: 'truth', language: Language.EN },
    { id: 281, word: 'veil', language: Language.EN },
    { id: 282, word: 'spirits', language: Language.EN },
    { id: 283, word: 'beyond', language: Language.EN },
    { id: 284, word: 'thin', language: Language.EN },
    { id: 285, word: 'whispers', language: Language.EN },
    { id: 286, word: 'message', language: Language.EN },
    { id: 287, word: 'fog', language: Language.EN },
    { id: 288, word: 'tomorrow', language: Language.EN },
    { id: 289, word: 'uncertain', language: Language.EN },
    { id: 290, word: 'pendulum', language: Language.EN },
    { id: 291, word: 'swing', language: Language.EN },
    { id: 293, word: 'buried', language: Language.EN },
    { id: 294, word: 'treasure', language: Language.EN },
    { id: 295, word: 'coins', language: Language.EN },
    { id: 296, word: 'fortune', language: Language.EN },
    { id: 297, word: 'fate', language: Language.EN },
    { id: 298, word: 'eye', language: Language.EN },
    { id: 299, word: 'third', language: Language.EN },
    { id: 300, word: 'vision', language: Language.EN },
    { id: 301, word: 'voices', language: Language.EN },
    { id: 302, word: 'ancient', language: Language.EN },
    { id: 303, word: 'dice', language: Language.EN },
    { id: 304, word: 'cast', language: Language.EN },
    { id: 305, word: 'decided', language: Language.EN },
    { id: 306, word: 'mirror', language: Language.EN },
    { id: 307, word: 'reveal', language: Language.EN },
    { id: 308, word: 'reality', language: Language.EN },
    { id: 309, word: 'pain', language: Language.EN },
    { id: 310, word: 'hurt', language: Language.EN },
    { id: 311, word: 'always', language: Language.EN },
    { id: 312, word: 'suffer', language: Language.EN },
    { id: 313, word: 'broken', language: Language.EN },
    { id: 314, word: 'never', language: Language.EN },
    { id: 315, word: 'failure', language: Language.EN },
    { id: 316, word: 'stalk', language: Language.EN },
    { id: 317, word: 'fall', language: Language.EN },
    { id: 318, word: 'betrayal', language: Language.EN },
    { id: 319, word: 'enemy', language: Language.EN },
    { id: 320, word: 'sickness', language: Language.EN },
    { id: 321, word: 'illness', language: Language.EN },
    { id: 322, word: 'bad', language: Language.EN },
    { id: 323, word: 'betray', language: Language.EN },
    { id: 324, word: 'weak', language: Language.EN },
    { id: 325, word: 'forgive', language: Language.EN },
    { id: 326, word: 'close', language: Language.EN },
    { id: 327, word: 'near', language: Language.EN },
    { id: 328, word: 'lurk', language: Language.EN },
    { id: 329, word: 'end', language: Language.EN },
    { id: 330, word: 'dead', language: Language.EN },
    { id: 331, word: 'rest', language: Language.EN },
    { id: 332, word: 'torment', language: Language.EN },
    { id: 333, word: 'haunt', language: Language.EN },
    { id: 334, word: 'darkness', language: Language.EN },
    { id: 335, word: 'black', language: Language.EN },
    { id: 336, word: 'evil', language: Language.EN },
    { id: 337, word: 'cruel', language: Language.EN },
    { id: 338, word: 'poverty', language: Language.EN },
    { id: 339, word: 'lose', language: Language.EN },
    { id: 340, word: 'ruin', language: Language.EN },
    { id: 341, word: 'poor', language: Language.EN },
    { id: 342, word: 'corrupt', language: Language.EN },
    { id: 343, word: 'lost', language: Language.EN },
    { id: 344, word: 'empty', language: Language.EN },
    { id: 345, word: 'demons', language: Language.EN },
    { id: 346, word: 'watch', language: Language.EN },
    { id: 347, word: 'no', language: Language.EN },
    { id: 348, word: 'win', language: Language.EN },
    { id: 349, word: 'kisses', language: Language.EN },
    { id: 350, word: 'happy', language: Language.EN },
    { id: 351, word: 'flying', language: Language.EN },
    { id: 352, word: 'joy', language: Language.EN },
    { id: 353, word: 'cupid', language: Language.EN },
    { id: 354, word: 'drunk', language: Language.EN },
    { id: 355, word: 'funny', language: Language.EN },
    { id: 356, word: 'crazy', language: Language.EN },
    { id: 357, word: 'boss', language: Language.EN },
    { id: 358, word: 'vacation', language: Language.EN },
    { id: 359, word: 'free', language: Language.EN },
    { id: 360, word: 'monday', language: Language.EN },
    { id: 361, word: 'fun', language: Language.EN },
    { id: 362, word: 'vitamins', language: Language.EN },
    { id: 363, word: 'laughter', language: Language.EN },
    { id: 364, word: 'dance', language: Language.EN },
    { id: 365, word: 'party', language: Language.EN },
    { id: 366, word: 'celebrate', language: Language.EN },
    { id: 367, word: 'grandma', language: Language.EN },
    { id: 368, word: 'cookies', language: Language.EN },
    { id: 369, word: 'sweet', language: Language.EN },
    { id: 370, word: 'ghosts', language: Language.EN },
    { id: 371, word: 'friendly', language: Language.EN },
    { id: 372, word: 'nice', language: Language.EN },
    { id: 373, word: 'afterlife', language: Language.EN },
    { id: 374, word: 'surprises', language: Language.EN },
    { id: 375, word: 'sparkle', language: Language.EN },
    { id: 392, word: 'gold', language: Language.EN },
    { id: 377, word: 'rain', language: Language.EN },
    { id: 378, word: 'wallet', language: Language.EN },
    { id: 379, word: 'fat', language: Language.EN },
    { id: 380, word: 'rich', language: Language.EN },
    { id: 381, word: 'soon', language: Language.EN },
    { id: 382, word: 'angels', language: Language.EN },
    { id: 383, word: 'heaven', language: Language.EN },
    { id: 384, word: 'aura', language: Language.EN },
    { id: 385, word: 'rainbow', language: Language.EN },
    { id: 386, word: 'color', language: Language.EN },
    { id: 387, word: 'question', language: Language.EN },
    { id: 388, word: 'silly', language: Language.EN },
    { id: 389, word: 'laugh', language: Language.EN },
    { id: 390, word: 'joke', language: Language.EN },
    { id: 391, word: 'giggle', language: Language.EN },
  ];

  console.log('Insertando keywords...');
  await prisma.keyword.createMany({ data: keywords });
  console.log(`Insertadas ${keywords.length} keywords\n`);

  // Definir TODAS las 144 respuestas usando ENUMS para type-safety
  const responses = [
    // WISE - ESPAÑOL (IDs 1-19)
    {
      id: 1,
      personality: Personality.WISE,
      category: Category.LOVE,
      language: Language.ES,
      text: 'El amor llegará pronto',
    },
    {
      id: 2,
      personality: Personality.WISE,
      category: Category.LOVE,
      language: Language.ES,
      text: 'Paciencia, tu alma gemela espera',
    },
    {
      id: 3,
      personality: Personality.WISE,
      category: Category.LOVE,
      language: Language.ES,
      text: 'Sana primero tu corazón',
    },
    {
      id: 4,
      personality: Personality.WISE,
      category: Category.CAREER,
      language: Language.ES,
      text: 'Nueva oportunidad se acerca',
    },
    {
      id: 5,
      personality: Personality.WISE,
      category: Category.CAREER,
      language: Language.ES,
      text: 'Sigue tu verdadera pasión',
    },
    {
      id: 6,
      personality: Personality.WISE,
      category: Category.HEALTH,
      language: Language.ES,
      text: 'Tu cuerpo sanará pronto',
    },
    {
      id: 7,
      personality: Personality.WISE,
      category: Category.HEALTH,
      language: Language.ES,
      text: 'Escucha las señales internas',
    },
    {
      id: 8,
      personality: Personality.WISE,
      category: Category.FAMILY,
      language: Language.ES,
      text: 'La familia se reconciliará',
    },
    {
      id: 9,
      personality: Personality.WISE,
      category: Category.FAMILY,
      language: Language.ES,
      text: 'Los lazos se fortalecerán',
    },
    {
      id: 10,
      personality: Personality.WISE,
      category: Category.DEATH,
      language: Language.ES,
      text: 'La muerte trae renacimiento',
    },
    {
      id: 11,
      personality: Personality.WISE,
      category: Category.DEATH,
      language: Language.ES,
      text: 'Los ancestros te protegen',
    },
    {
      id: 12,
      personality: Personality.WISE,
      category: Category.FUTURE,
      language: Language.ES,
      text: 'Cambios positivos se aproximan',
    },
    {
      id: 13,
      personality: Personality.WISE,
      category: Category.FUTURE,
      language: Language.ES,
      text: 'Tu destino es brillante',
    },
    {
      id: 14,
      personality: Personality.WISE,
      category: Category.MONEY,
      language: Language.ES,
      text: 'Abundancia fluirá hacia ti',
    },
    {
      id: 15,
      personality: Personality.WISE,
      category: Category.MONEY,
      language: Language.ES,
      text: 'Ahorra para tiempos mejores',
    },
    {
      id: 16,
      personality: Personality.WISE,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: 'Tu espíritu está despertando',
    },
    {
      id: 17,
      personality: Personality.WISE,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: 'Medita y encontrarás respuestas',
    },
    {
      id: 18,
      personality: Personality.WISE,
      category: Category.GENERAL,
      language: Language.ES,
      text: 'Todo tiene su momento',
    },
    {
      id: 19,
      personality: Personality.WISE,
      category: Category.GENERAL,
      language: Language.ES,
      text: 'Confía en el proceso',
    },

    // CRYPTIC - ESPAÑOL (IDs 20-37)
    {
      id: 20,
      personality: Personality.CRYPTIC,
      category: Category.LOVE,
      language: Language.ES,
      text: 'Tres lunas, un corazón',
    },
    {
      id: 21,
      personality: Personality.CRYPTIC,
      category: Category.LOVE,
      language: Language.ES,
      text: 'La rosa oculta espinas',
    },
    {
      id: 22,
      personality: Personality.CRYPTIC,
      category: Category.CAREER,
      language: Language.ES,
      text: 'El camino se bifurca',
    },
    {
      id: 23,
      personality: Personality.CRYPTIC,
      category: Category.CAREER,
      language: Language.ES,
      text: 'Sombras en la oficina',
    },
    {
      id: 24,
      personality: Personality.CRYPTIC,
      category: Category.HEALTH,
      language: Language.ES,
      text: 'El cuerpo susurra secretos',
    },
    {
      id: 25,
      personality: Personality.CRYPTIC,
      category: Category.HEALTH,
      language: Language.ES,
      text: 'Veneno o medicina, tú decides',
    },
    {
      id: 26,
      personality: Personality.CRYPTIC,
      category: Category.FAMILY,
      language: Language.ES,
      text: 'Sangre llama a sangre',
    },
    {
      id: 27,
      personality: Personality.CRYPTIC,
      category: Category.FAMILY,
      language: Language.ES,
      text: 'Secretos bajo el tejado',
    },
    {
      id: 28,
      personality: Personality.CRYPTIC,
      category: Category.DEATH,
      language: Language.ES,
      text: 'El velo se adelgaza',
    },
    {
      id: 29,
      personality: Personality.CRYPTIC,
      category: Category.DEATH,
      language: Language.ES,
      text: 'Susurros del más allá',
    },
    {
      id: 30,
      personality: Personality.CRYPTIC,
      category: Category.FUTURE,
      language: Language.ES,
      text: 'Niebla oculta el mañana',
    },
    {
      id: 31,
      personality: Personality.CRYPTIC,
      category: Category.FUTURE,
      language: Language.ES,
      text: 'El péndulo oscila lentamente',
    },
    {
      id: 32,
      personality: Personality.CRYPTIC,
      category: Category.MONEY,
      language: Language.ES,
      text: 'Oro enterrado espera',
    },
    {
      id: 33,
      personality: Personality.CRYPTIC,
      category: Category.MONEY,
      language: Language.ES,
      text: 'Monedas caen, monedas suben',
    },
    {
      id: 34,
      personality: Personality.CRYPTIC,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: 'El tercer ojo parpadea',
    },
    {
      id: 35,
      personality: Personality.CRYPTIC,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: 'Voces antiguas te llaman',
    },
    {
      id: 36,
      personality: Personality.CRYPTIC,
      category: Category.GENERAL,
      language: Language.ES,
      text: 'Las cartas están echadas',
    },
    {
      id: 37,
      personality: Personality.CRYPTIC,
      category: Category.GENERAL,
      language: Language.ES,
      text: 'El espejo muestra verdades',
    },

    // DARK - ESPAÑOL (IDs 38-55)
    {
      id: 38,
      personality: Personality.DARK,
      category: Category.LOVE,
      language: Language.ES,
      text: 'El amor duele siempre',
    },
    {
      id: 39,
      personality: Personality.DARK,
      category: Category.LOVE,
      language: Language.ES,
      text: 'Corazones rotos no sanan',
    },
    {
      id: 40,
      personality: Personality.DARK,
      category: Category.CAREER,
      language: Language.ES,
      text: 'El fracaso te acecha',
    },
    {
      id: 41,
      personality: Personality.DARK,
      category: Category.CAREER,
      language: Language.ES,
      text: 'Traición en tu trabajo',
    },
    {
      id: 42,
      personality: Personality.DARK,
      category: Category.HEALTH,
      language: Language.ES,
      text: 'La enfermedad se acerca',
    },
    {
      id: 43,
      personality: Personality.DARK,
      category: Category.HEALTH,
      language: Language.ES,
      text: 'Tu cuerpo te traiciona',
    },
    {
      id: 44,
      personality: Personality.DARK,
      category: Category.FAMILY,
      language: Language.ES,
      text: 'La sangre no perdona',
    },
    {
      id: 45,
      personality: Personality.DARK,
      category: Category.FAMILY,
      language: Language.ES,
      text: 'Traición viene de cerca',
    },
    {
      id: 46,
      personality: Personality.DARK,
      category: Category.DEATH,
      language: Language.ES,
      text: 'La muerte ronda cerca',
    },
    {
      id: 47,
      personality: Personality.DARK,
      category: Category.DEATH,
      language: Language.ES,
      text: 'Los muertos no descansan',
    },
    {
      id: 48,
      personality: Personality.DARK,
      category: Category.FUTURE,
      language: Language.ES,
      text: 'Oscuridad en tu camino',
    },
    {
      id: 49,
      personality: Personality.DARK,
      category: Category.FUTURE,
      language: Language.ES,
      text: 'El destino es cruel',
    },
    {
      id: 50,
      personality: Personality.DARK,
      category: Category.MONEY,
      language: Language.ES,
      text: 'La pobreza te espera',
    },
    {
      id: 51,
      personality: Personality.DARK,
      category: Category.MONEY,
      language: Language.ES,
      text: 'El dinero corrompe todo',
    },
    {
      id: 52,
      personality: Personality.DARK,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: 'Tu alma está perdida',
    },
    {
      id: 53,
      personality: Personality.DARK,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: 'Demonios te observan siempre',
    },
    {
      id: 54,
      personality: Personality.DARK,
      category: Category.GENERAL,
      language: Language.ES,
      text: 'No hay esperanza aquí',
    },
    {
      id: 55,
      personality: Personality.DARK,
      category: Category.GENERAL,
      language: Language.ES,
      text: 'El mal siempre gana',
    },

    // PLAYFUL - ESPAÑOL (IDs 56-73)
    {
      id: 56,
      personality: Personality.PLAYFUL,
      category: Category.LOVE,
      language: Language.ES,
      text: '¡Besos vienen volando!',
    },
    {
      id: 57,
      personality: Personality.PLAYFUL,
      category: Category.LOVE,
      language: Language.ES,
      text: 'Cupido está borracho',
    },
    {
      id: 58,
      personality: Personality.PLAYFUL,
      category: Category.CAREER,
      language: Language.ES,
      text: '¡Jefe nuevo, vida nueva!',
    },
    {
      id: 59,
      personality: Personality.PLAYFUL,
      category: Category.CAREER,
      language: Language.ES,
      text: 'Los lunes serán divertidos',
    },
    {
      id: 60,
      personality: Personality.PLAYFUL,
      category: Category.HEALTH,
      language: Language.ES,
      text: '¡Vitaminas y risas funcionan!',
    },
    {
      id: 61,
      personality: Personality.PLAYFUL,
      category: Category.HEALTH,
      language: Language.ES,
      text: 'Baila y sana todo',
    },
    {
      id: 62,
      personality: Personality.PLAYFUL,
      category: Category.FAMILY,
      language: Language.ES,
      text: '¡Fiesta familiar se acerca!',
    },
    {
      id: 63,
      personality: Personality.PLAYFUL,
      category: Category.FAMILY,
      language: Language.ES,
      text: 'La abuela trae galletas',
    },
    {
      id: 64,
      personality: Personality.PLAYFUL,
      category: Category.DEATH,
      language: Language.ES,
      text: 'Los fantasmas son amigables',
    },
    {
      id: 65,
      personality: Personality.PLAYFUL,
      category: Category.DEATH,
      language: Language.ES,
      text: '¡Fiesta en el más allá!',
    },
    {
      id: 66,
      personality: Personality.PLAYFUL,
      category: Category.FUTURE,
      language: Language.ES,
      text: '¡Sorpresas locas vienen!',
    },
    {
      id: 67,
      personality: Personality.PLAYFUL,
      category: Category.FUTURE,
      language: Language.ES,
      text: 'El futuro brilla mucho',
    },
    {
      id: 68,
      personality: Personality.PLAYFUL,
      category: Category.MONEY,
      language: Language.ES,
      text: '¡Lluvia de monedas doradas!',
    },
    {
      id: 69,
      personality: Personality.PLAYFUL,
      category: Category.MONEY,
      language: Language.ES,
      text: 'Tu billetera engordará pronto',
    },
    {
      id: 70,
      personality: Personality.PLAYFUL,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: '¡Los ángeles hacen fiesta!',
    },
    {
      id: 71,
      personality: Personality.PLAYFUL,
      category: Category.SPIRITUALITY,
      language: Language.ES,
      text: 'Tu aura brilla arcoíris',
    },
    {
      id: 72,
      personality: Personality.PLAYFUL,
      category: Category.GENERAL,
      language: Language.ES,
      text: '¡Vaya pregunta más loca!',
    },
    {
      id: 73,
      personality: Personality.PLAYFUL,
      category: Category.GENERAL,
      language: Language.ES,
      text: 'Los espíritus se ríen',
    },

    // WISE - ENGLISH (IDs 74-91)
    {
      id: 74,
      personality: Personality.WISE,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Love arrives when ready',
    },
    {
      id: 75,
      personality: Personality.WISE,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Patience brings true connection',
    },
    {
      id: 76,
      personality: Personality.WISE,
      category: Category.CAREER,
      language: Language.EN,
      text: 'New opportunity approaches soon',
    },
    {
      id: 77,
      personality: Personality.WISE,
      category: Category.CAREER,
      language: Language.EN,
      text: 'Follow your true calling',
    },
    {
      id: 78,
      personality: Personality.WISE,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Your body will heal',
    },
    {
      id: 79,
      personality: Personality.WISE,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Listen to inner wisdom',
    },
    {
      id: 80,
      personality: Personality.WISE,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Family bonds strengthen now',
    },
    {
      id: 81,
      personality: Personality.WISE,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Forgiveness heals all wounds',
    },
    {
      id: 82,
      personality: Personality.WISE,
      category: Category.DEATH,
      language: Language.EN,
      text: 'Death brings transformation',
    },
    {
      id: 83,
      personality: Personality.WISE,
      category: Category.DEATH,
      language: Language.EN,
      text: 'Ancestors guide your path',
    },
    {
      id: 84,
      personality: Personality.WISE,
      category: Category.FUTURE,
      language: Language.EN,
      text: 'Bright changes approach fast',
    },
    {
      id: 85,
      personality: Personality.WISE,
      category: Category.FUTURE,
      language: Language.EN,
      text: 'Your destiny shines bright',
    },
    {
      id: 86,
      personality: Personality.WISE,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Abundance flows to you',
    },
    {
      id: 87,
      personality: Personality.WISE,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Save for better times',
    },
    {
      id: 88,
      personality: Personality.WISE,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Your spirit awakens now',
    },
    {
      id: 89,
      personality: Personality.WISE,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Meditation brings clear answers',
    },
    {
      id: 90,
      personality: Personality.WISE,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'Everything has its time',
    },
    {
      id: 91,
      personality: Personality.WISE,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'Trust the process completely',
    },

    // CRYPTIC - ENGLISH (IDs 92-109)
    {
      id: 92,
      personality: Personality.CRYPTIC,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Three moons, one heart',
    },
    {
      id: 93,
      personality: Personality.CRYPTIC,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Roses hide sharp thorns',
    },
    {
      id: 94,
      personality: Personality.CRYPTIC,
      category: Category.CAREER,
      language: Language.EN,
      text: 'The path splits ahead',
    },
    {
      id: 95,
      personality: Personality.CRYPTIC,
      category: Category.CAREER,
      language: Language.EN,
      text: 'Shadows in the office',
    },
    {
      id: 96,
      personality: Personality.CRYPTIC,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Body whispers dark secrets',
    },
    {
      id: 97,
      personality: Personality.CRYPTIC,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Poison or cure awaits',
    },
    {
      id: 98,
      personality: Personality.CRYPTIC,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Blood calls to blood',
    },
    {
      id: 99,
      personality: Personality.CRYPTIC,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Secrets beneath the roof',
    },
    {
      id: 100,
      personality: Personality.CRYPTIC,
      category: Category.DEATH,
      language: Language.EN,
      text: 'The veil grows thin',
    },
    {
      id: 101,
      personality: Personality.CRYPTIC,
      category: Category.DEATH,
      language: Language.EN,
      text: 'Whispers from beyond call',
    },
    {
      id: 102,
      personality: Personality.CRYPTIC,
      category: Category.FUTURE,
      language: Language.EN,
      text: "Fog hides tomorrow's face",
    },
    {
      id: 103,
      personality: Personality.CRYPTIC,
      category: Category.FUTURE,
      language: Language.EN,
      text: 'The pendulum swings slowly',
    },
    {
      id: 104,
      personality: Personality.CRYPTIC,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Buried gold awaits discovery',
    },
    {
      id: 105,
      personality: Personality.CRYPTIC,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Coins fall, coins rise',
    },
    {
      id: 106,
      personality: Personality.CRYPTIC,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Third eye blinks slowly',
    },
    {
      id: 107,
      personality: Personality.CRYPTIC,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Ancient voices call you',
    },
    {
      id: 108,
      personality: Personality.CRYPTIC,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'The dice are cast',
    },
    {
      id: 109,
      personality: Personality.CRYPTIC,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'Mirrors reveal hidden truths',
    },

    // DARK - ENGLISH (IDs 110-127)
    {
      id: 110,
      personality: Personality.DARK,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Love always brings pain',
    },
    {
      id: 111,
      personality: Personality.DARK,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Broken hearts never heal',
    },
    {
      id: 112,
      personality: Personality.DARK,
      category: Category.CAREER,
      language: Language.EN,
      text: 'Failure stalks you closely',
    },
    {
      id: 113,
      personality: Personality.DARK,
      category: Category.CAREER,
      language: Language.EN,
      text: 'Betrayal at work awaits',
    },
    {
      id: 114,
      personality: Personality.DARK,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Sickness approaches you fast',
    },
    {
      id: 115,
      personality: Personality.DARK,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Your body betrays you',
    },
    {
      id: 116,
      personality: Personality.DARK,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Blood never forgives betrayal',
    },
    {
      id: 117,
      personality: Personality.DARK,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Betrayal comes from family',
    },
    {
      id: 118,
      personality: Personality.DARK,
      category: Category.DEATH,
      language: Language.EN,
      text: 'Death lurks very near',
    },
    {
      id: 119,
      personality: Personality.DARK,
      category: Category.DEATH,
      language: Language.EN,
      text: 'The dead never rest',
    },
    {
      id: 120,
      personality: Personality.DARK,
      category: Category.FUTURE,
      language: Language.EN,
      text: 'Darkness fills your path',
    },
    {
      id: 121,
      personality: Personality.DARK,
      category: Category.FUTURE,
      language: Language.EN,
      text: 'Fate remains cruel always',
    },
    {
      id: 122,
      personality: Personality.DARK,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Poverty awaits you soon',
    },
    {
      id: 123,
      personality: Personality.DARK,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Money corrupts everything always',
    },
    {
      id: 124,
      personality: Personality.DARK,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Your soul is lost',
    },
    {
      id: 125,
      personality: Personality.DARK,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Demons watch you always',
    },
    {
      id: 126,
      personality: Personality.DARK,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'No hope exists here',
    },
    {
      id: 127,
      personality: Personality.DARK,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'Evil always wins everything',
    },

    // PLAYFUL - ENGLISH (IDs 128-145)
    {
      id: 128,
      personality: Personality.PLAYFUL,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Kisses flying your way!',
    },
    {
      id: 129,
      personality: Personality.PLAYFUL,
      category: Category.LOVE,
      language: Language.EN,
      text: 'Cupid is drunk again',
    },
    {
      id: 130,
      personality: Personality.PLAYFUL,
      category: Category.CAREER,
      language: Language.EN,
      text: 'Boss vacation coming soon!',
    },
    {
      id: 131,
      personality: Personality.PLAYFUL,
      category: Category.CAREER,
      language: Language.EN,
      text: 'Mondays become fun days',
    },
    {
      id: 132,
      personality: Personality.PLAYFUL,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Vitamins and laughter work!',
    },
    {
      id: 133,
      personality: Personality.PLAYFUL,
      category: Category.HEALTH,
      language: Language.EN,
      text: 'Dance heals everything quickly',
    },
    {
      id: 134,
      personality: Personality.PLAYFUL,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Family party coming soon!',
    },
    {
      id: 135,
      personality: Personality.PLAYFUL,
      category: Category.FAMILY,
      language: Language.EN,
      text: 'Grandma brings cookies today',
    },
    {
      id: 136,
      personality: Personality.PLAYFUL,
      category: Category.DEATH,
      language: Language.EN,
      text: 'Ghosts are friendly here',
    },
    {
      id: 137,
      personality: Personality.PLAYFUL,
      category: Category.DEATH,
      language: Language.EN,
      text: 'Afterlife party never stops!',
    },
    {
      id: 138,
      personality: Personality.PLAYFUL,
      category: Category.FUTURE,
      language: Language.EN,
      text: 'Crazy surprises coming fast!',
    },
    {
      id: 139,
      personality: Personality.PLAYFUL,
      category: Category.FUTURE,
      language: Language.EN,
      text: 'Future sparkles with joy',
    },
    {
      id: 140,
      personality: Personality.PLAYFUL,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Golden coins rain down!',
    },
    {
      id: 141,
      personality: Personality.PLAYFUL,
      category: Category.MONEY,
      language: Language.EN,
      text: 'Wallet gets fat soon',
    },
    {
      id: 142,
      personality: Personality.PLAYFUL,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Angels throwing a party!',
    },
    {
      id: 143,
      personality: Personality.PLAYFUL,
      category: Category.SPIRITUALITY,
      language: Language.EN,
      text: 'Your aura sparkles rainbows',
    },
    {
      id: 144,
      personality: Personality.PLAYFUL,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'What a silly question!',
    },
    {
      id: 145,
      personality: Personality.PLAYFUL,
      category: Category.GENERAL,
      language: Language.EN,
      text: 'Spirits giggle at you',
    },
  ];

  console.log('Insertando responses...');
  await prisma.fallbackResponse.createMany({ data: responses });
  console.log(`Insertadas ${responses.length} responses\n`);

  // Definir TODAS las 720 relaciones (144 respuestas * 5 keywords cada una)
  const relations = [
    // R-1 (wise, love, es)
    { responseId: 1, keywordId: 1 },
    { responseId: 1, keywordId: 2 },
    { responseId: 1, keywordId: 3 },
    { responseId: 1, keywordId: 4 },
    { responseId: 1, keywordId: 5 },
    // R-2 (wise, love, es)
    { responseId: 2, keywordId: 6 },
    { responseId: 2, keywordId: 7 },
    { responseId: 2, keywordId: 8 },
    { responseId: 2, keywordId: 9 },
    { responseId: 2, keywordId: 10 },
    // R-3 (wise, love, es)
    { responseId: 3, keywordId: 11 },
    { responseId: 3, keywordId: 4 },
    { responseId: 3, keywordId: 12 },
    { responseId: 3, keywordId: 13 },
    { responseId: 3, keywordId: 14 },
    // R-4 (wise, career, es)
    { responseId: 4, keywordId: 15 },
    { responseId: 4, keywordId: 16 },
    { responseId: 4, keywordId: 17 },
    { responseId: 4, keywordId: 18 },
    { responseId: 4, keywordId: 19 },
    // R-5 (wise, career, es)
    { responseId: 5, keywordId: 20 },
    { responseId: 5, keywordId: 21 },
    { responseId: 5, keywordId: 22 },
    { responseId: 5, keywordId: 23 },
    { responseId: 5, keywordId: 24 },
    // R-6 (wise, health, es)
    { responseId: 6, keywordId: 25 },
    { responseId: 6, keywordId: 11 },
    { responseId: 6, keywordId: 26 },
    { responseId: 6, keywordId: 27 },
    { responseId: 6, keywordId: 28 },
    // R-7 (wise, health, es)
    { responseId: 7, keywordId: 29 },
    { responseId: 7, keywordId: 26 },
    { responseId: 7, keywordId: 30 },
    { responseId: 7, keywordId: 25 },
    { responseId: 7, keywordId: 31 },
    // R-8 (wise, family, es)
    { responseId: 8, keywordId: 32 },
    { responseId: 8, keywordId: 33 },
    { responseId: 8, keywordId: 34 },
    { responseId: 8, keywordId: 35 },
    { responseId: 8, keywordId: 36 },
    // R-9 (wise, family, es)
    { responseId: 9, keywordId: 37 },
    { responseId: 9, keywordId: 32 },
    { responseId: 9, keywordId: 38 },
    { responseId: 9, keywordId: 39 },
    { responseId: 9, keywordId: 1 },
    // R-10 (wise, death, es)
    { responseId: 10, keywordId: 40 },
    { responseId: 10, keywordId: 41 },
    { responseId: 10, keywordId: 42 },
    { responseId: 10, keywordId: 43 },
    { responseId: 10, keywordId: 44 },
    // R-11 (wise, death, es)
    { responseId: 11, keywordId: 45 },
    { responseId: 11, keywordId: 46 },
    { responseId: 11, keywordId: 47 },
    { responseId: 11, keywordId: 48 },
    { responseId: 11, keywordId: 49 },
    // R-12 (wise, future, es)
    { responseId: 12, keywordId: 50 },
    { responseId: 12, keywordId: 51 },
    { responseId: 12, keywordId: 52 },
    { responseId: 12, keywordId: 53 },
    { responseId: 12, keywordId: 10 },
    // R-13 (wise, future, es)
    { responseId: 13, keywordId: 10 },
    { responseId: 13, keywordId: 54 },
    { responseId: 13, keywordId: 50 },
    { responseId: 13, keywordId: 55 },
    { responseId: 13, keywordId: 56 },
    // R-14 (wise, money, es)
    { responseId: 14, keywordId: 57 },
    { responseId: 14, keywordId: 58 },
    { responseId: 14, keywordId: 59 },
    { responseId: 14, keywordId: 60 },
    { responseId: 14, keywordId: 61 },
    // R-15 (wise, money, es)
    { responseId: 15, keywordId: 62 },
    { responseId: 15, keywordId: 57 },
    { responseId: 15, keywordId: 50 },
    { responseId: 15, keywordId: 63 },
    { responseId: 15, keywordId: 64 },
    // R-16 (wise, spirituality, es)
    { responseId: 16, keywordId: 65 },
    { responseId: 16, keywordId: 66 },
    { responseId: 16, keywordId: 6 },
    { responseId: 16, keywordId: 67 },
    { responseId: 16, keywordId: 68 },
    // R-17 (wise, spirituality, es)
    { responseId: 17, keywordId: 69 },
    { responseId: 17, keywordId: 70 },
    { responseId: 17, keywordId: 34 },
    { responseId: 17, keywordId: 71 },
    { responseId: 17, keywordId: 72 },
    // R-18 (wise, general, es)
    { responseId: 18, keywordId: 14 },
    { responseId: 18, keywordId: 73 },
    { responseId: 18, keywordId: 8 },
    { responseId: 18, keywordId: 9 },
    { responseId: 18, keywordId: 10 },
    // R-19 (wise, general, es)
    { responseId: 19, keywordId: 74 },
    { responseId: 19, keywordId: 75 },
    { responseId: 19, keywordId: 76 },
    { responseId: 19, keywordId: 77 },
    { responseId: 19, keywordId: 24 },
    // R-20 (cryptic, love, es)
    { responseId: 20, keywordId: 1 },
    { responseId: 20, keywordId: 78 },
    { responseId: 20, keywordId: 79 },
    { responseId: 20, keywordId: 4 },
    { responseId: 20, keywordId: 80 },
    // R-21 (cryptic, love, es)
    { responseId: 21, keywordId: 1 },
    { responseId: 21, keywordId: 81 },
    { responseId: 21, keywordId: 82 },
    { responseId: 21, keywordId: 83 },
    { responseId: 21, keywordId: 84 },
    // R-22 (cryptic, career, es)
    { responseId: 22, keywordId: 15 },
    { responseId: 22, keywordId: 24 },
    { responseId: 22, keywordId: 85 },
    { responseId: 22, keywordId: 86 },
    { responseId: 22, keywordId: 10 },
    // R-23 (cryptic, career, es)
    { responseId: 23, keywordId: 15 },
    { responseId: 23, keywordId: 87 },
    { responseId: 23, keywordId: 84 },
    { responseId: 23, keywordId: 89 },
    { responseId: 23, keywordId: 88 },
    // R-24 (cryptic, health, es)
    { responseId: 24, keywordId: 25 },
    { responseId: 24, keywordId: 26 },
    { responseId: 24, keywordId: 90 },
    { responseId: 24, keywordId: 29 },
    { responseId: 24, keywordId: 30 },
    // R-25 (cryptic, health, es)
    { responseId: 25, keywordId: 25 },
    { responseId: 25, keywordId: 129 },
    { responseId: 25, keywordId: 157 },
    { responseId: 25, keywordId: 86 },
    { responseId: 25, keywordId: 85 },
    // R-26 (cryptic, family, es)
    { responseId: 26, keywordId: 32 },
    { responseId: 26, keywordId: 133 },
    { responseId: 26, keywordId: 111 },
    { responseId: 26, keywordId: 37 },
    { responseId: 26, keywordId: 10 },
    // R-27 (cryptic, family, es)
    { responseId: 27, keywordId: 32 },
    { responseId: 27, keywordId: 90 },
    { responseId: 27, keywordId: 190 },
    { responseId: 27, keywordId: 83 },
    { responseId: 27, keywordId: 116 },
    // R-28 (cryptic, death, es)
    { responseId: 28, keywordId: 40 },
    { responseId: 28, keywordId: 91 },
    { responseId: 28, keywordId: 47 },
    { responseId: 28, keywordId: 92 },
    { responseId: 28, keywordId: 93 },
    // R-29 (cryptic, death, es)
    { responseId: 29, keywordId: 40 },
    { responseId: 29, keywordId: 94 },
    { responseId: 29, keywordId: 47 },
    { responseId: 29, keywordId: 95 },
    { responseId: 29, keywordId: 96 },
    // R-30 (cryptic, future, es)
    { responseId: 30, keywordId: 50 },
    { responseId: 30, keywordId: 97 },
    { responseId: 30, keywordId: 83 },
    { responseId: 30, keywordId: 98 },
    { responseId: 30, keywordId: 99 },
    // R-31 (cryptic, future, es)
    { responseId: 31, keywordId: 50 },
    { responseId: 31, keywordId: 100 },
    { responseId: 31, keywordId: 14 },
    { responseId: 31, keywordId: 10 },
    { responseId: 31, keywordId: 101 },
    // R-32 (cryptic, money, es)
    { responseId: 32, keywordId: 57 },
    { responseId: 32, keywordId: 102 },
    { responseId: 32, keywordId: 103 },
    { responseId: 32, keywordId: 83 },
    { responseId: 32, keywordId: 8 },
    // R-33 (cryptic, money, es)
    { responseId: 33, keywordId: 57 },
    { responseId: 33, keywordId: 104 },
    { responseId: 33, keywordId: 101 },
    { responseId: 33, keywordId: 105 },
    { responseId: 33, keywordId: 10 },
    // R-34 (cryptic, spirituality, es)
    { responseId: 34, keywordId: 65 },
    { responseId: 34, keywordId: 106 },
    { responseId: 34, keywordId: 107 },
    { responseId: 34, keywordId: 66 },
    { responseId: 34, keywordId: 108 },
    // R-35 (cryptic, spirituality, es)
    { responseId: 35, keywordId: 65 },
    { responseId: 35, keywordId: 109 },
    { responseId: 35, keywordId: 110 },
    { responseId: 35, keywordId: 111 },
    { responseId: 35, keywordId: 95 },
    // R-36 (cryptic, general, es)
    { responseId: 36, keywordId: 10 },
    { responseId: 36, keywordId: 112 },
    { responseId: 36, keywordId: 113 },
    { responseId: 36, keywordId: 114 },
    { responseId: 36, keywordId: 50 },
    // R-37 (cryptic, general, es)
    { responseId: 37, keywordId: 116 },
    { responseId: 37, keywordId: 115 },
    { responseId: 37, keywordId: 117 },
    { responseId: 37, keywordId: 118 },
    { responseId: 37, keywordId: 119 },
    // R-38 (dark, love, es)
    { responseId: 38, keywordId: 1 },
    { responseId: 38, keywordId: 13 },
    { responseId: 38, keywordId: 120 },
    { responseId: 38, keywordId: 121 },
    { responseId: 38, keywordId: 4 },
    // R-39 (dark, love, es)
    { responseId: 39, keywordId: 4 },
    { responseId: 39, keywordId: 122 },
    { responseId: 39, keywordId: 13 },
    { responseId: 39, keywordId: 11 },
    { responseId: 39, keywordId: 123 },
    // R-40 (dark, career, es)
    { responseId: 40, keywordId: 15 },
    { responseId: 40, keywordId: 124 },
    { responseId: 40, keywordId: 125 },
    { responseId: 40, keywordId: 84 },
    { responseId: 40, keywordId: 126 },
    // R-41 (dark, career, es)
    { responseId: 41, keywordId: 15 },
    { responseId: 41, keywordId: 127 },
    { responseId: 41, keywordId: 128 },
    { responseId: 41, keywordId: 84 },
    { responseId: 41, keywordId: 89 },
    // R-42 (dark, health, es)
    { responseId: 42, keywordId: 25 },
    { responseId: 42, keywordId: 27 },
    { responseId: 42, keywordId: 84 },
    { responseId: 42, keywordId: 13 },
    { responseId: 42, keywordId: 129 },
    // R-43 (dark, health, es)
    { responseId: 43, keywordId: 26 },
    { responseId: 43, keywordId: 127 },
    { responseId: 43, keywordId: 13 },
    { responseId: 43, keywordId: 27 },
    { responseId: 43, keywordId: 130 },
    // R-44 (dark, family, es)
    { responseId: 44, keywordId: 32 },
    { responseId: 44, keywordId: 133 },
    { responseId: 44, keywordId: 36 },
    { responseId: 44, keywordId: 131 },
    { responseId: 44, keywordId: 13 },
    // R-45 (dark, family, es)
    { responseId: 45, keywordId: 32 },
    { responseId: 45, keywordId: 127 },
    { responseId: 45, keywordId: 132 },
    { responseId: 45, keywordId: 84 },
    { responseId: 45, keywordId: 13 },
    // R-46 (dark, death, es)
    { responseId: 46, keywordId: 40 },
    { responseId: 46, keywordId: 132 },
    { responseId: 46, keywordId: 84 },
    { responseId: 46, keywordId: 44 },
    { responseId: 46, keywordId: 134 },
    // R-47 (dark, death, es)
    { responseId: 47, keywordId: 135 },
    { responseId: 47, keywordId: 47 },
    { responseId: 47, keywordId: 136 },
    { responseId: 47, keywordId: 137 },
    { responseId: 47, keywordId: 6 },
    // R-48 (dark, future, es)
    { responseId: 48, keywordId: 50 },
    { responseId: 48, keywordId: 138 },
    { responseId: 48, keywordId: 84 },
    { responseId: 48, keywordId: 139 },
    { responseId: 48, keywordId: 129 },
    // R-49 (dark, future, es)
    { responseId: 49, keywordId: 10 },
    { responseId: 49, keywordId: 140 },
    { responseId: 49, keywordId: 13 },
    { responseId: 49, keywordId: 120 },
    { responseId: 49, keywordId: 50 },
    // R-50 (dark, money, es)
    { responseId: 50, keywordId: 57 },
    { responseId: 50, keywordId: 141 },
    { responseId: 50, keywordId: 142 },
    { responseId: 50, keywordId: 143 },
    { responseId: 50, keywordId: 126 },
    // R-51 (dark, money, es)
    { responseId: 51, keywordId: 57 },
    { responseId: 51, keywordId: 144 },
    { responseId: 51, keywordId: 129 },
    { responseId: 51, keywordId: 142 },
    { responseId: 51, keywordId: 6 },
    // R-52 (dark, spirituality, es)
    { responseId: 52, keywordId: 6 },
    { responseId: 52, keywordId: 145 },
    { responseId: 52, keywordId: 138 },
    { responseId: 52, keywordId: 146 },
    { responseId: 52, keywordId: 65 },
    // R-53 (dark, spirituality, es)
    { responseId: 53, keywordId: 147 },
    { responseId: 53, keywordId: 148 },
    { responseId: 53, keywordId: 84 },
    { responseId: 53, keywordId: 129 },
    { responseId: 53, keywordId: 65 },
    // R-54 (dark, general, es)
    { responseId: 54, keywordId: 56 },
    { responseId: 54, keywordId: 149 },
    { responseId: 54, keywordId: 150 },
    { responseId: 54, keywordId: 138 },
    { responseId: 54, keywordId: 44 },
    // R-55 (dark, general, es)
    { responseId: 55, keywordId: 129 },
    { responseId: 55, keywordId: 121 },
    { responseId: 55, keywordId: 151 },
    { responseId: 55, keywordId: 142 },
    { responseId: 55, keywordId: 138 },
    { responseId: 55, keywordId: 10 },
    // R-56 (playful, love, es)
    { responseId: 56, keywordId: 1 },
    { responseId: 56, keywordId: 152 },
    { responseId: 56, keywordId: 153 },
    { responseId: 56, keywordId: 154 },
    { responseId: 56, keywordId: 155 },
    // R-57 (playful, love, es)
    { responseId: 57, keywordId: 1 },
    { responseId: 57, keywordId: 156 },
    { responseId: 57, keywordId: 157 },
    { responseId: 57, keywordId: 158 },
    { responseId: 57, keywordId: 159 },
    // R-58 (playful, career, es)
    { responseId: 58, keywordId: 15 },
    { responseId: 58, keywordId: 160 },
    { responseId: 58, keywordId: 19 },
    { responseId: 58, keywordId: 101 },
    { responseId: 58, keywordId: 153 },
    // R-59 (playful, career, es)
    { responseId: 59, keywordId: 15 },
    { responseId: 59, keywordId: 161 },
    { responseId: 59, keywordId: 162 },
    { responseId: 59, keywordId: 153 },
    { responseId: 59, keywordId: 155 },
    // R-60 (playful, health, es)
    { responseId: 60, keywordId: 25 },
    { responseId: 60, keywordId: 163 },
    { responseId: 60, keywordId: 164 },
    { responseId: 60, keywordId: 153 },
    { responseId: 60, keywordId: 11 },
    // R-61 (playful, health, es)
    { responseId: 61, keywordId: 25 },
    { responseId: 61, keywordId: 165 },
    { responseId: 61, keywordId: 11 },
    { responseId: 61, keywordId: 153 },
    { responseId: 61, keywordId: 26 },
    // R-62 (playful, family, es)
    { responseId: 62, keywordId: 32 },
    { responseId: 62, keywordId: 166 },
    { responseId: 62, keywordId: 153 },
    { responseId: 62, keywordId: 167 },
    { responseId: 62, keywordId: 35 },
    // R-63 (playful, family, es)
    { responseId: 63, keywordId: 32 },
    { responseId: 63, keywordId: 168 },
    { responseId: 63, keywordId: 169 },
    { responseId: 63, keywordId: 1 },
    { responseId: 63, keywordId: 170 },
    // R-64 (playful, death, es)
    { responseId: 64, keywordId: 40 },
    { responseId: 64, keywordId: 171 },
    { responseId: 64, keywordId: 172 },
    { responseId: 64, keywordId: 65 },
    { responseId: 64, keywordId: 173 },
    // R-65 (playful, death, es)
    { responseId: 65, keywordId: 40 },
    { responseId: 65, keywordId: 166 },
    { responseId: 65, keywordId: 96 },
    { responseId: 65, keywordId: 65 },
    { responseId: 65, keywordId: 153 },
    // R-66 (playful, future, es)
    { responseId: 66, keywordId: 50 },
    { responseId: 66, keywordId: 174 },
    { responseId: 66, keywordId: 159 },
    { responseId: 66, keywordId: 53 },
    { responseId: 66, keywordId: 153 },
    // R-67 (playful, future, es)
    { responseId: 67, keywordId: 50 },
    { responseId: 67, keywordId: 175 },
    { responseId: 67, keywordId: 55 },
    { responseId: 67, keywordId: 153 },
    { responseId: 67, keywordId: 173 },
    // R-68 (playful, money, es)
    { responseId: 68, keywordId: 57 },
    { responseId: 68, keywordId: 104 },
    { responseId: 68, keywordId: 176 },
    { responseId: 68, keywordId: 102 },
    { responseId: 68, keywordId: 60 },
    // R-69 (playful, money, es)
    { responseId: 69, keywordId: 57 },
    { responseId: 69, keywordId: 177 },
    { responseId: 69, keywordId: 178 },
    { responseId: 69, keywordId: 179 },
    { responseId: 69, keywordId: 180 },
    // R-70 (playful, spirituality, es)
    { responseId: 70, keywordId: 65 },
    { responseId: 70, keywordId: 181 },
    { responseId: 70, keywordId: 166 },
    { responseId: 70, keywordId: 153 },
    { responseId: 70, keywordId: 182 },
    // R-71 (playful, spirituality, es)
    { responseId: 71, keywordId: 65 },
    { responseId: 71, keywordId: 183 },
    { responseId: 71, keywordId: 184 },
    { responseId: 71, keywordId: 175 },
    { responseId: 71, keywordId: 185 },
    // R-72 (playful, general, es)
    { responseId: 72, keywordId: 186 },
    { responseId: 72, keywordId: 187 },
    { responseId: 72, keywordId: 162 },
    { responseId: 72, keywordId: 158 },
    { responseId: 72, keywordId: 188 },
    // R-73 (playful, general, es)
    { responseId: 73, keywordId: 47 },
    { responseId: 73, keywordId: 189 },
    { responseId: 73, keywordId: 153 },
    { responseId: 73, keywordId: 158 },
    { responseId: 73, keywordId: 155 },
    // R-74 (wise, love, en)
    { responseId: 74, keywordId: 191 },
    { responseId: 74, keywordId: 192 },
    { responseId: 74, keywordId: 193 },
    { responseId: 74, keywordId: 194 },
    { responseId: 74, keywordId: 195 },
    // R-75 (wise, love, en)
    { responseId: 75, keywordId: 191 },
    { responseId: 75, keywordId: 196 },
    { responseId: 75, keywordId: 197 },
    { responseId: 75, keywordId: 198 },
    { responseId: 75, keywordId: 199 },
    // R-76 (wise, career, en)
    { responseId: 76, keywordId: 200 },
    { responseId: 76, keywordId: 201 },
    { responseId: 76, keywordId: 202 },
    { responseId: 76, keywordId: 203 },
    { responseId: 76, keywordId: 204 },
    // R-77 (wise, career, en)
    { responseId: 77, keywordId: 202 },
    { responseId: 77, keywordId: 205 },
    { responseId: 77, keywordId: 206 },
    { responseId: 77, keywordId: 207 },
    { responseId: 77, keywordId: 208 },
    // R-78 (wise, health, en)
    { responseId: 78, keywordId: 209 },
    { responseId: 78, keywordId: 210 },
    { responseId: 78, keywordId: 211 },
    { responseId: 78, keywordId: 212 },
    { responseId: 78, keywordId: 213 },
    // R-79 (wise, health, en)
    { responseId: 79, keywordId: 209 },
    { responseId: 79, keywordId: 214 },
    { responseId: 79, keywordId: 215 },
    { responseId: 79, keywordId: 211 },
    { responseId: 79, keywordId: 216 },
    // R-80 (wise, family, en)
    { responseId: 80, keywordId: 217 },
    { responseId: 80, keywordId: 218 },
    { responseId: 80, keywordId: 219 },
    { responseId: 80, keywordId: 191 },
    { responseId: 80, keywordId: 220 },
    // R-81 (wise, family, en)
    { responseId: 81, keywordId: 217 },
    { responseId: 81, keywordId: 221 },
    { responseId: 81, keywordId: 210 },
    { responseId: 81, keywordId: 222 },
    { responseId: 81, keywordId: 191 },
    // R-82 (wise, death, en)
    { responseId: 82, keywordId: 223 },
    { responseId: 82, keywordId: 224 },
    { responseId: 82, keywordId: 225 },
    { responseId: 82, keywordId: 226 },
    { responseId: 82, keywordId: 227 },
    // R-83 (wise, death, en)
    { responseId: 83, keywordId: 228 },
    { responseId: 83, keywordId: 229 },
    { responseId: 83, keywordId: 230 },
    { responseId: 83, keywordId: 231 },
    { responseId: 83, keywordId: 223 },
    // R-84 (wise, future, en)
    { responseId: 84, keywordId: 232 },
    { responseId: 84, keywordId: 233 },
    { responseId: 84, keywordId: 234 },
    { responseId: 84, keywordId: 235 },
    { responseId: 84, keywordId: 236 },
    // R-85 (wise, future, en)
    { responseId: 85, keywordId: 236 },
    { responseId: 85, keywordId: 232 },
    { responseId: 85, keywordId: 234 },
    { responseId: 85, keywordId: 237 },
    { responseId: 85, keywordId: 238 },
    // R-86 (wise, money, en)
    { responseId: 86, keywordId: 239 },
    { responseId: 86, keywordId: 240 },
    { responseId: 86, keywordId: 241 },
    { responseId: 86, keywordId: 242 },
    { responseId: 86, keywordId: 243 },
    // R-87 (wise, money, en)
    { responseId: 87, keywordId: 239 },
    { responseId: 87, keywordId: 244 },
    { responseId: 87, keywordId: 232 },
    { responseId: 87, keywordId: 215 },
    { responseId: 87, keywordId: 245 },
    // R-88 (wise, spirituality, en)
    { responseId: 88, keywordId: 230 },
    { responseId: 88, keywordId: 246 },
    { responseId: 88, keywordId: 195 },
    { responseId: 88, keywordId: 247 },
    { responseId: 88, keywordId: 248 },
    // R-89 (wise, spirituality, en)
    { responseId: 89, keywordId: 249 },
    { responseId: 89, keywordId: 250 },
    { responseId: 89, keywordId: 222 },
    { responseId: 89, keywordId: 230 },
    { responseId: 89, keywordId: 251 },
    // R-90 (wise, general, en)
    { responseId: 90, keywordId: 252 },
    { responseId: 90, keywordId: 196 },
    { responseId: 90, keywordId: 199 },
    { responseId: 90, keywordId: 236 },
    { responseId: 90, keywordId: 253 },
    // R-91 (wise, general, en)
    { responseId: 91, keywordId: 254 },
    { responseId: 91, keywordId: 255 },
    { responseId: 91, keywordId: 256 },
    { responseId: 91, keywordId: 257 },
    { responseId: 91, keywordId: 208 },
    // R-92 (cryptic, love, en)
    { responseId: 92, keywordId: 191 },
    { responseId: 92, keywordId: 258 },
    { responseId: 92, keywordId: 259 },
    { responseId: 92, keywordId: 192 },
    { responseId: 92, keywordId: 260 },
    // R-93 (cryptic, love, en)
    { responseId: 93, keywordId: 191 },
    { responseId: 93, keywordId: 261 },
    { responseId: 93, keywordId: 262 },
    { responseId: 93, keywordId: 263 },
    { responseId: 93, keywordId: 264 },
    // R-94 (cryptic, career, en)
    { responseId: 94, keywordId: 200 },
    { responseId: 94, keywordId: 208 },
    { responseId: 94, keywordId: 265 },
    { responseId: 94, keywordId: 266 },
    { responseId: 94, keywordId: 267 },
    // R-95 (cryptic, career, en)
    { responseId: 95, keywordId: 200 },
    { responseId: 95, keywordId: 268 },
    { responseId: 95, keywordId: 264 },
    { responseId: 95, keywordId: 269 },
    { responseId: 95, keywordId: 270 },
    // R-96 (cryptic, health, en)
    { responseId: 96, keywordId: 209 },
    { responseId: 96, keywordId: 211 },
    { responseId: 96, keywordId: 271 },
    { responseId: 96, keywordId: 272 },
    { responseId: 96, keywordId: 273 },
    // R-97 (cryptic, health, en)
    { responseId: 97, keywordId: 209 },
    { responseId: 97, keywordId: 274 },
    { responseId: 97, keywordId: 275 },
    { responseId: 97, keywordId: 265 },
    { responseId: 97, keywordId: 276 },
    // R-98 (cryptic, family, en)
    { responseId: 98, keywordId: 217 },
    { responseId: 98, keywordId: 277 },
    { responseId: 98, keywordId: 278 },
    { responseId: 98, keywordId: 218 },
    { responseId: 98, keywordId: 236 },
    // R-99 (cryptic, family, en)
    { responseId: 99, keywordId: 217 },
    { responseId: 99, keywordId: 271 },
    { responseId: 99, keywordId: 279 },
    { responseId: 99, keywordId: 263 },
    { responseId: 99, keywordId: 280 },
    // R-100 (cryptic, death, en)
    { responseId: 100, keywordId: 223 },
    { responseId: 100, keywordId: 281 },
    { responseId: 100, keywordId: 282 },
    { responseId: 100, keywordId: 283 },
    { responseId: 100, keywordId: 284 },
    // R-101 (cryptic, death, en)
    { responseId: 101, keywordId: 223 },
    { responseId: 101, keywordId: 285 },
    { responseId: 101, keywordId: 283 },
    { responseId: 101, keywordId: 282 },
    { responseId: 101, keywordId: 286 },
    // R-102 (cryptic, future, en)
    { responseId: 102, keywordId: 232 },
    { responseId: 102, keywordId: 287 },
    { responseId: 102, keywordId: 263 },
    { responseId: 102, keywordId: 288 },
    { responseId: 102, keywordId: 289 },
    // R-103 (cryptic, future, en)
    { responseId: 103, keywordId: 232 },
    { responseId: 103, keywordId: 290 },
    { responseId: 103, keywordId: 252 },
    { responseId: 103, keywordId: 236 },
    { responseId: 103, keywordId: 291 },
    // R-104 (cryptic, money, en)
    { responseId: 104, keywordId: 239 },
    { responseId: 104, keywordId: 392 },
    { responseId: 104, keywordId: 293 },
    { responseId: 104, keywordId: 294 },
    { responseId: 104, keywordId: 263 },
    // R-105 (cryptic, money, en)
    { responseId: 105, keywordId: 239 },
    { responseId: 105, keywordId: 295 },
    { responseId: 105, keywordId: 227 },
    { responseId: 105, keywordId: 296 },
    { responseId: 105, keywordId: 297 },
    // R-106 (cryptic, spirituality, en)
    { responseId: 106, keywordId: 230 },
    { responseId: 106, keywordId: 298 },
    { responseId: 106, keywordId: 299 },
    { responseId: 106, keywordId: 246 },
    { responseId: 106, keywordId: 300 },
    // R-107 (cryptic, spirituality, en)
    { responseId: 107, keywordId: 230 },
    { responseId: 107, keywordId: 301 },
    { responseId: 107, keywordId: 302 },
    { responseId: 107, keywordId: 278 },
    { responseId: 107, keywordId: 286 },
    // R-108 (cryptic, general, en)
    { responseId: 108, keywordId: 297 },
    { responseId: 108, keywordId: 303 },
    { responseId: 108, keywordId: 304 },
    { responseId: 108, keywordId: 236 },
    { responseId: 108, keywordId: 305 },
    // R-109 (cryptic, general, en)
    { responseId: 109, keywordId: 280 },
    { responseId: 109, keywordId: 306 },
    { responseId: 109, keywordId: 307 },
    { responseId: 109, keywordId: 263 },
    { responseId: 109, keywordId: 308 },
    // R-110 (dark, love, en)
    { responseId: 110, keywordId: 191 },
    { responseId: 110, keywordId: 309 },
    { responseId: 110, keywordId: 310 },
    { responseId: 110, keywordId: 311 },
    { responseId: 110, keywordId: 312 },
    // R-111 (dark, love, en)
    { responseId: 111, keywordId: 192 },
    { responseId: 111, keywordId: 313 },
    { responseId: 111, keywordId: 314 },
    { responseId: 111, keywordId: 210 },
    { responseId: 111, keywordId: 309 },
    // R-112 (dark, career, en)
    { responseId: 112, keywordId: 200 },
    { responseId: 112, keywordId: 315 },
    { responseId: 112, keywordId: 316 },
    { responseId: 112, keywordId: 264 },
    { responseId: 112, keywordId: 317 },
    // R-113 (dark, career, en)
    { responseId: 113, keywordId: 200 },
    { responseId: 113, keywordId: 318 },
    { responseId: 113, keywordId: 319 },
    { responseId: 113, keywordId: 264 },
    { responseId: 113, keywordId: 254 },
    // R-114 (dark, health, en)
    { responseId: 114, keywordId: 209 },
    { responseId: 114, keywordId: 320 },
    { responseId: 114, keywordId: 264 },
    { responseId: 114, keywordId: 321 },
    { responseId: 114, keywordId: 322 },
    // R-115 (dark, health, en)
    { responseId: 115, keywordId: 211 },
    { responseId: 115, keywordId: 323 },
    { responseId: 115, keywordId: 309 },
    { responseId: 115, keywordId: 321 },
    { responseId: 115, keywordId: 324 },
    // R-116 (dark, family, en)
    { responseId: 116, keywordId: 217 },
    { responseId: 116, keywordId: 277 },
    { responseId: 116, keywordId: 325 },
    { responseId: 116, keywordId: 318 },
    { responseId: 116, keywordId: 309 },
    // R-117 (dark, family, en)
    { responseId: 117, keywordId: 217 },
    { responseId: 117, keywordId: 318 },
    { responseId: 117, keywordId: 326 },
    { responseId: 117, keywordId: 264 },
    { responseId: 117, keywordId: 310 },
    // R-118 (dark, death, en)
    { responseId: 118, keywordId: 223 },
    { responseId: 118, keywordId: 327 },
    { responseId: 118, keywordId: 264 },
    { responseId: 118, keywordId: 328 },
    { responseId: 118, keywordId: 329 },
    // R-119 (dark, death, en)
    { responseId: 119, keywordId: 330 },
    { responseId: 119, keywordId: 282 },
    { responseId: 119, keywordId: 331 },
    { responseId: 119, keywordId: 332 },
    { responseId: 119, keywordId: 333 },
    // R-120 (dark, future, en)
    { responseId: 120, keywordId: 232 },
    { responseId: 120, keywordId: 334 },
    { responseId: 120, keywordId: 264 },
    { responseId: 120, keywordId: 335 },
    { responseId: 120, keywordId: 336 },
    // R-121 (dark, future, en)
    { responseId: 121, keywordId: 297 },
    { responseId: 121, keywordId: 337 },
    { responseId: 121, keywordId: 309 },
    { responseId: 121, keywordId: 312 },
    { responseId: 121, keywordId: 232 },
    // R-122 (dark, money, en)
    { responseId: 122, keywordId: 239 },
    { responseId: 122, keywordId: 338 },
    { responseId: 122, keywordId: 339 },
    { responseId: 122, keywordId: 340 },
    { responseId: 122, keywordId: 341 },
    // R-123 (dark, money, en)
    { responseId: 123, keywordId: 239 },
    { responseId: 123, keywordId: 342 },
    { responseId: 123, keywordId: 336 },
    { responseId: 123, keywordId: 339 },
    { responseId: 123, keywordId: 195 },
    // R-124 (dark, spirituality, en)
    { responseId: 124, keywordId: 195 },
    { responseId: 124, keywordId: 343 },
    { responseId: 124, keywordId: 334 },
    { responseId: 124, keywordId: 344 },
    { responseId: 124, keywordId: 230 },
    // R-125 (dark, spirituality, en)
    { responseId: 125, keywordId: 345 },
    { responseId: 125, keywordId: 346 },
    { responseId: 125, keywordId: 264 },
    { responseId: 125, keywordId: 336 },
    { responseId: 125, keywordId: 230 },
    // R-126 (dark, general, en)
    { responseId: 126, keywordId: 238 },
    { responseId: 126, keywordId: 347 },
    { responseId: 126, keywordId: 343 },
    { responseId: 126, keywordId: 334 },
    { responseId: 126, keywordId: 329 },
    // R-127 (dark, general, en)
    { responseId: 127, keywordId: 336 },
    { responseId: 127, keywordId: 311 },
    { responseId: 127, keywordId: 348 },
    { responseId: 127, keywordId: 339 },
    { responseId: 127, keywordId: 334 },
    { responseId: 127, keywordId: 297 },
    // R-128 (playful, love, en)
    { responseId: 128, keywordId: 191 },
    { responseId: 128, keywordId: 349 },
    { responseId: 128, keywordId: 350 },
    { responseId: 128, keywordId: 351 },
    { responseId: 128, keywordId: 352 },
    // R-129 (playful, love, en)
    { responseId: 129, keywordId: 191 },
    { responseId: 129, keywordId: 353 },
    { responseId: 129, keywordId: 354 },
    { responseId: 129, keywordId: 355 },
    { responseId: 129, keywordId: 356 },
    // R-130 (playful, career, en)
    { responseId: 130, keywordId: 200 },
    { responseId: 130, keywordId: 357 },
    { responseId: 130, keywordId: 358 },
    { responseId: 130, keywordId: 350 },
    { responseId: 130, keywordId: 359 },
    // R-131 (playful, career, en)
    { responseId: 131, keywordId: 200 },
    { responseId: 131, keywordId: 360 },
    { responseId: 131, keywordId: 361 },
    { responseId: 131, keywordId: 350 },
    { responseId: 131, keywordId: 352 },
    // R-132 (playful, health, en)
    { responseId: 132, keywordId: 209 },
    { responseId: 132, keywordId: 362 },
    { responseId: 132, keywordId: 363 },
    { responseId: 132, keywordId: 350 },
    { responseId: 132, keywordId: 210 },
    // R-133 (playful, health, en)
    { responseId: 133, keywordId: 209 },
    { responseId: 133, keywordId: 364 },
    { responseId: 133, keywordId: 210 },
    { responseId: 133, keywordId: 352 },
    { responseId: 133, keywordId: 211 },
    // R-134 (playful, family, en)
    { responseId: 134, keywordId: 217 },
    { responseId: 134, keywordId: 365 },
    { responseId: 134, keywordId: 352 },
    { responseId: 134, keywordId: 366 },
    { responseId: 134, keywordId: 361 },
    // R-135 (playful, family, en)
    { responseId: 135, keywordId: 217 },
    { responseId: 135, keywordId: 367 },
    { responseId: 135, keywordId: 368 },
    { responseId: 135, keywordId: 191 },
    { responseId: 135, keywordId: 369 },
    // R-136 (playful, death, en)
    { responseId: 136, keywordId: 223 },
    { responseId: 136, keywordId: 370 },
    { responseId: 136, keywordId: 371 },
    { responseId: 136, keywordId: 230 },
    { responseId: 136, keywordId: 372 },
    // R-137 (playful, death, en)
    { responseId: 137, keywordId: 223 },
    { responseId: 137, keywordId: 365 },
    { responseId: 137, keywordId: 373 },
    { responseId: 137, keywordId: 230 },
    { responseId: 137, keywordId: 361 },
    // R-138 (playful, future, en)
    { responseId: 138, keywordId: 232 },
    { responseId: 138, keywordId: 374 },
    { responseId: 138, keywordId: 356 },
    { responseId: 138, keywordId: 235 },
    { responseId: 138, keywordId: 361 },
    // R-139 (playful, future, en)
    { responseId: 139, keywordId: 232 },
    { responseId: 139, keywordId: 375 },
    { responseId: 139, keywordId: 352 },
    { responseId: 139, keywordId: 234 },
    { responseId: 139, keywordId: 350 },
    // R-140 (playful, money, en)
    { responseId: 140, keywordId: 239 },
    { responseId: 140, keywordId: 295 },
    { responseId: 140, keywordId: 392 },
    { responseId: 140, keywordId: 377 },
    { responseId: 140, keywordId: 242 },
    // R-141 (playful, money, en)
    { responseId: 141, keywordId: 239 },
    { responseId: 141, keywordId: 378 },
    { responseId: 141, keywordId: 379 },
    { responseId: 141, keywordId: 380 },
    { responseId: 141, keywordId: 381 },
    // R-142 (playful, spirituality, en)
    { responseId: 142, keywordId: 230 },
    { responseId: 142, keywordId: 382 },
    { responseId: 142, keywordId: 365 },
    { responseId: 142, keywordId: 352 },
    { responseId: 142, keywordId: 383 },
    // R-143 (playful, spirituality, en)
    { responseId: 143, keywordId: 230 },
    { responseId: 143, keywordId: 384 },
    { responseId: 143, keywordId: 385 },
    { responseId: 143, keywordId: 375 },
    { responseId: 143, keywordId: 386 },
    // R-144 (playful, general, en)
    { responseId: 144, keywordId: 387 },
    { responseId: 144, keywordId: 388 },
    { responseId: 144, keywordId: 355 },
    { responseId: 144, keywordId: 389 },
    { responseId: 144, keywordId: 390 },
    // R-145 (playful, general, en)
    { responseId: 145, keywordId: 282 },
    { responseId: 145, keywordId: 391 },
    { responseId: 145, keywordId: 389 },
    { responseId: 145, keywordId: 355 },
    { responseId: 145, keywordId: 350 },
  ];

  console.log('Insertando relaciones (response ↔ keyword)...');
  await prisma.responseKeyword.createMany({ data: relations });
  console.log(`Insertadas ${relations.length} relaciones\n`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
